Adding first set of API tests
DFE-Digital/academies-academisation-api pull request #126
Opened 2022-09-27 13:52 UTC by dangood84

2022-09-27 14:02 UTC, cshnimble commented on CypressTests/package.json
> +  "name": "dansacademisationapicypresstests",
Worth renaming this now it's part of the academisation-api project

2022-09-27 14:04 UTC, cshnimble commented on CypressTests/package.json
> +  "scripts": {
Worth updating the scripts section to include options for running Cypress tests.
e.g. see how [a2b internal](https://github.com/DFE-Digital/a2b-internal/blob/main/ApplyToBecomeInternal/ApplyToBecomeCypressTests/package.json#L7) does it

2022-09-27 14:13 UTC, cshnimble commented
I would also recommend updating the repo's README.md with some instructions on how to set up and run the Cypress tests - see [a2b internal](https://github.com/DFE-Digital/a2b-internal) for an example

2022-09-27 14:13 UTC, cshnimble requested changes

2022-09-27 14:13 UTC, cshnimble commented on CypressTests/cypress/e2e/Get-UpdateApplication.cy.js
> +    Cypress.config('baseUrl', 'http://academies-academisation-api-dev.azurewebsites.net/')
This should ideally be an environment variable, as with API key above

2022-09-27 14:13 UTC, cshnimble commented on CypressTests/cypress/e2e/Get-UpdateApplication.cy.js
> +import {UnauthorisedUserCannotUpdatePayload} from '../support/payloads/UnauthorisedUserCannotUpdateBody.spec'
One for a future enhancement - as these payloads are very similar but with a few changed bits of data, could we instead have one import of a positive test payload and just modify the data within the test?

e.g.
import { goodPayload } from '/path/to/payload'
[...]
let somePayload = goodPayload         // uses the happy path payload
somePayload.someField = 'badData'  // now modify data for failure condition

2022-10-26 09:43 UTC, cshnimble approved these changes

2022-11-22 17:18 UTC, cshnimble commented
@dangood84 Are these tests still valid? If not they need updating for this PR - it's been sat stale a long time

2022-11-22 17:46 UTC, dangood84 commented
> 

Hey Chris, Should still be valid.  Have my changes merged in OK.  I saw the prompts in VS Code to merge and update for the tests to use Application ID 27.  Have these changes taken affect from my last push?

Many thanks

2022-11-23 11:36 UTC, merged