Add list of Key Vault users
DFE-Digital/academies-academisation-api pull request #146
Opened 2022-10-19 12:19 UTC by Stretch96

* Allows providing a list of users that require access to the Key Vault tfvars secrets
* The values should be the User Principle Name found in AD

2022-10-19 14:42 UTC, mec requested changes
Terrafrom looks good! Couple of housekeeping things.

2022-10-19 14:42 UTC, mec commented on terraform/README.md
> +| <a name="input_key_vault_access_users"></a> [key\_vault\_access\_users](#input\_key\_vault\_access\_users) | List if users that require access to the Key Vault where tfvars are stored. This should
Type "List of"

2022-10-19 14:42 UTC, mec commented on terraform/terraform.tfvars.example
> +  "someone_example.com#EXT#@tenantname.onmicrosoft.com",
I would like to understand where we get these 'Principle Names' in the documentation.

2022-10-19 14:42 UTC, mec commented on terraform/variables.tf
> +  description = "List if users that require access to the Key Vault where tfvars are stored. This should be a list of all users that need to run terraform"
Same typo here.

2022-10-19 15:47 UTC, Stretch96 commented on terraform/variables.tf
> +  description = "List if users that require access to the Key Vault where tfvars are stored. This should be a list of all users that need to run terraform"
👍

2022-10-19 15:47 UTC, Stretch96 commented on terraform/README.md
> +| <a name="input_key_vault_access_users"></a> [key\_vault\_access\_users](#input\_key\_vault\_access\_users) | List if users that require access to the Key Vault where tfvars are stored. This should
👍

2022-10-20 09:57 UTC, mec approved these changes
🚢

2022-10-20 09:59 UTC, mec approved these changes
🚢

2022-10-20 09:59 UTC, mec approved these changes
🚢

2022-10-20 09:59 UTC, merged

2022-10-20 10:00 UTC, mec commented
🚢 🚢 🚢  I can't approve this but ship it!