Add Production build and push workflow
DFE-Digital/academies-academisation-api pull request #193
Opened 2023-01-05 16:17 UTC by Stretch96

* Builds and pushes a given release tag to Azure ACR Production environment

2023-01-06 09:39 UTC, jordan-beard approved these changes

2023-01-06 10:23 UTC, DrizzlyOwl requested changes

2023-01-06 10:23 UTC, DrizzlyOwl commented on .github/workflows/build-and-push-image-production.yml
> +    needs: set-test-release-version
```diff
-needs: set-test-release-version
+needs: set-production-release-version
```

2023-01-06 10:23 UTC, DrizzlyOwl commented on .github/workflows/build-and-push-image-production.yml
> +            TAGS="$TAGS,${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:${{needs.set-test-release-version.outputs.version}}"
```diff
-TAGS="$TAGS,${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:${{needs.set-test-release-version.outputs.version}}"
+TAGS="$TAGS,${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:${{needs.set-production-release-version.outputs.version}}"

2023-01-06 10:23 UTC, DrizzlyOwl commented on .github/workflows/build-and-push-image-production.yml
> +          ref: ${{needs.set-test-release-version.outputs.version}}
```diff
-ref: ${{needs.set-test-release-version.outputs.version}}
+ref: ${{needs.set-production-release-version.outputs.version}}
```

2023-01-09 10:13 UTC, jordan-beard approved these changes

2023-01-09 10:18 UTC, DrizzlyOwl approved these changes

2023-01-09 10:19 UTC, merged